#!/bin/bash

password=$(jq -r '.password' < $HOME/device.json)
sshpass -p $password ssh -o StrictHostKeyChecking=no pi@$192.168.0.101

sshpass -p $password scp -o StrictHostKeyChecking=no $HOME/device.json pi@$192.168.0.101:/home/pi
